### ISSUE TITLE
Would this work for 8-bit grayscale images?

### ISSUE THREAD

**Issue by jmo-gelsight** [usercode/WPF.ImageEffects#2]
This shader appears to deal only in floating-point pixels.  I know next to nothing about DirectX and how the image pipeline works.  If I were showing a bitmap created as 8-bit grayscale, would this shader work for that?   Or would I need to try to learn how to write my own shader.

**Comment by usercode** [comment]
I'm sure that the image control use everytime the same pixel format regardless of the file format.
