### ISSUE TITLE
Brightness problems with transparent images

### ISSUE THREAD

**Issue by AcruxDevelopment** [usercode/WPF.ImageEffects#4]
# Problem
I intalled this via `dotnet add package WPF.ImageEffects --version 1.5.0` and I found that when I apply the `Brightness` property to a positive number, the transparent parts of the image get tinted white.
However, this does not happen when I apply the property to a negative value or zero.

# Notes
I have a single instance of the `BrightnessContrastEffect` class, where that instance is applied to a `Grid` full of `Image`s.

The instance is created programmatically:
```
public BrightnessContrastEffect BrightnessContrastEffect { get; } = new BrightnessContrastEffect();
...
BrightnessContrastEffect.Brightness = 0.5;
```

And the instance is attached this way:
`SpriteGrid.Effect = BrightnessContrastEffect;`

I am not sure if the problem is related to the fact that the shader also picks up other elements that are not part of the grid itself, but are rendered behind it, thus applying the shader to everything within the grid's boundaries.

Also, having to apply the effects to the images individually isnt a solution for me because it would cause the effect to "accumulate" in semi-transparent images

---

Thanks for your help.

**Comment by usercode** [comment]
The shader do not touch the alpha value of the pixels.

Maybe the control has a background color which is modified, too?

**Comment by AcruxDevelopment** [comment]
Nop, i created a brand new WPF.NET C# project for testing, just added an image, added the effect to it and the issue persists:

![image](https://github.com/user-attachments/assets/c12c27fe-7e8f-408f-8be2-f40f5e340435)

![image](https://github.com/user-attachments/assets/b5d0ea5b-16ed-4d2e-8dd6-dceda4e516d1)

![image](https://github.com/user-attachments/assets/82c3f6dd-466f-421f-8ff2-51a8ccf6a3f4)

As shown in the image, i selected a random png asset i had, placed it in a gray background colored window (it can be any color, it was just to differenciate between the place where the buggy white tint takes place and the rest of the window), attached the effect, and that's the result.

**Comment by usercode** [comment]
I'm sure your image doesn't contains full transparent pixels.

If your image contains partial transparent pixels, it will combine the color from the background. That's correct.

Here is an example. The blue rectangle is a full transparent area. (This grid has the blue background color.)

brightness = -1

![grafik](https://github.com/user-attachments/assets/0778ed80-9c3a-4db8-8e7d-ce10da5b2ed2)

brightness = 1

![grafik](https://github.com/user-attachments/assets/33189893-afbb-4c5a-9c59-84f1dc89d0a6)

Please use the example demo from this respository and test again.
